
# --- MAIN OPTIONS ---
admin username: LL4wliet    # Set it without @ symbol.
api token: 779864631:AAHZqhP43R8ah6RFCx43pcaygHGFSIGt3l8

databases:
  user:
    drivername: postgresql
    username: cyberpunk
    password: punk
    host: 127.0.0.1
    port: 5432
    database: fairybang
  girls:
    drivername: postgresql
    username: cyberpunk
    password: punk
    host: 127.0.0.1
    port: 5432
    database: girls

# --- OTHER OPTIONS ---
enable tor: True

# Debug: True (polling) / False (webhooks).
debug: True

# Support email address.
mail: test@test.com


# --- REQUIRE LISTS ---
qiwi:
  - +7 921 777 77 77
  - +7 922 888 88 88

countries:
  - 🇷🇺 Россия

promocodes:
  FB12NMQ4:
    promo_discount: 5
    promo_valid_from: 2020-6-2
    promo_valid_to: 2020-6-20
  FB89LKJ2:
    promo_discount: 10
    promo_valid_from: 2020-5-1
    promo_valid_to: 2020-5-12
